### ISSUE TITLE
Version 4 deployment checklist

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/masonite4#122]
This issue is to track the progress for releasing version 4:

- [ ] Finish Documentation
    - [x] Views
    - [x] Facades
    - [x] Routing
    - [x] Release cycle
    - [x] Middleware
    - [x] CSRF Docs
    - [x] Notifications (done here => https://github.com/MasoniteFramework/docs/pull/162)
    - [x] Guards / registering guards
    - [x] Static Assets
    - [x] Validation
    - [x] Controllers
    - [x] Request
    - [x] Testing
    - [x] Commands
    - [ ] Package Development
    - [x] Response
    - [x] Helpers
    - [x] Creating a Blog
    - [x] Authentication
    - [x] Secure Headers Middleware
    - [ ] Whats New
    - [x] Upgrade Guide
    - [x] Contributing guide
- [x] Update cookie cutter project
    * Need to update the start project repo to manage how new projects are created
- [x] Create a very simple project and follow all the install steps and hit as many features as possible
- [x] Create Beta Version (v4.0b0)
- [x] Fix any issues we find during testing
- [x] Final review of documentation
- [x] Release version 4 (v4.0.0)

**Comment by josephmancuso** [comment]
Might be worth a look at these How to guides to upgrade them:

* [Build Email Verification from Scratch With Masonite Framework and JSON Web Tokens](https://dev.to/nioperas06/build-email-verification-from-scratch-with-masonite-framework-and-json-web-tokens-mf7)
* [Deploying a Masonite Application to Heroku](https://dev.to/masonite/deploying-a-masonite-application-to-heroku-45jp)
* [How To Deploy Masonite to PythonAnywhere](https://dev.to/masonite/deploying-masonite-to-pythonanywhere-26lj)
* [How-To: Use RabbitMQ with Masonite 2.0 queues](https://dev.to/masonite/how-to-use-rabbitmq-with-masonite-20-queues-4105)
* [How To Use The Repository Pattern with Masonite](https://dev.to/masonite/repository-pattern-with-masonite-4a0n)
* [Making Masonite and Laravel Mix work together](https://dev.to/nioperas06/lets-make-masonite-framework-and-laravel-mix-work-together--3lbj)

**Comment by goophps** [comment]
I like your framework very much and look forward to the official release. Excuse me, when is it expected to be released?

**Comment by goophps** [comment]
I am really looking forward to it. I have come here every day recently.

**Comment by goophps** [comment]
good
